server:
  port: 8080

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    sqs:
      endpoint: http://localhost:4566
    sns:
      endpoint: http://localhost:4566
    dynamodb:
      endpoint: http://localhost:4566
      access-key: localstack
      secret-key: localstack
    s3:
      endpoint: http://localhost:4566
      path-style-access-enabled: true

dynamodb:
  region: "us-east-1"
  trust-all-certificates: true
  endpoint-override: http://localhost:4566


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
  main:
    allow-bean-definition-overriding: true
storage:
  bucket: payment-bucket
