package br.com.zoro.kafkapub.repository.domain

import br.com.zoro.kafkapub.repository.converter.LocalDateTimeConverter
import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.time.LocalDateTime


@DynamoDBTable(tableName = "tb_processing")
data class PaymentSentDomain (

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    val id: String? = null,

    @DynamoDBAttribute(attributeName = "date_time_processing")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter::class)
    val dateTime: LocalDateTime? = null,

    @DynamoDBAttribute(attributeName = "e2e")
    val end2end: String? = null,

    @DynamoDBAttribute(attributeName = "namePayer")
    val namePayer: String? = null,

    @DynamoDBAttribute(attributeName = "nameReceiver")
    val nameReceiver: String? = null,

    @DynamoDBAttribute(attributeName = "amount")
    val amount: String? = null
)